trigger:
- main

pool:
  name: stock-pool

#  vmImage: 'ubuntu-latest'


steps:

- powershell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force
  displayName: 'Fix PowerShell Policy'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: python --version
  displayName: 'Check Python Version'

- script: pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python app/main.py
  displayName: 'Run trading system'