trigger:
- main

pool:
  name: stock-pool

#  vmImage: 'ubuntu-latest'


steps:
# Fix execution policy
- powershell: |
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
  displayName: 'Fix PowerShell Execution Policy'

# Install Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

#- task: UsePythonVersion@0
#  inputs:
#    versionSpec: '3.10'

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python app/main.py
  displayName: 'Run trading system'